# Metadata for your pipeline:
---
name: jmvdcollectie
description: Zet de jmvdcollectie datadump om naar EDM RDF voor publicatie op Europeana

# This is optional, by default it will be stored in the data directory of the pipeline using filename 'statements.nt'
destination: file://jmvdcollectie.nt

# The individual stages for your pipeline
stages:
  - name: "Stage 1 - Schema2EDM"
    iterator:
      query: file://iterator.rq
      batchSize: 1000
      endpoint: http://localhost:3030/jmvdcollectie/sparql
    generator:
      - query: file://edm-generator.rq
        batchSize: 1000