# Metadata for your pipeline:
---
name: $DATASET
description: Zet de $DATASET datadump om naar EDM RDF voor publicatie op Europeana

# This is optional, by default it will be stored in the data directory of the pipeline using filename 'statements.nt'
destination: file://$DATASET.nt

# The individual stages for your pipeline
stages:
  - name: "Stage 1 - Schema2EDM"
    iterator:
      query: file://iterator-stage-1.rq
      batchSize: 1000
      endpoint: http://localhost:3030/${DATASET}/sparql
    generator:
      - query: file://generator-stage-1.rq
        batchSize: 1000